//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerOrders = new HashSet<CustomerOrder>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Cart { get; set; }
        public string WishList { get; set; }
        public Nullable<bool> Newsletter { get; set; }
        public Nullable<int> CustomerGroup { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual CustomerGroup CustomerGroup1 { get; set; }
        public virtual CustomerStatu CustomerStatu { get; set; }
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
