//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<decimal> OrderCost { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Notes { get; set; }
    
        public virtual CustomerOrder CustomerOrder { get; set; }
        public virtual Product Product { get; set; }
    }
}
