//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMeta
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string MetaKey { get; set; }
        public string MetaValue { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Notes { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
